import { PENTADEKANY_2_6, PENTADEKANY_4_6 } from './pentadekany-data.js';
console.log("2_6 Trianies:", PENTADEKANY_2_6["Trianies"]?.length);
console.log("2_6 Pentanies:", PENTADEKANY_2_6["Pentanies"]?.length);
console.log("2_6 Hexanies:", PENTADEKANY_2_6["Hexanies"]?.length);
console.log("2_6 Dekanies:", PENTADEKANY_2_6["Dekanies"]?.length);
console.log("4_6 Dyanies:", PENTADEKANY_4_6["Dyanies"]?.length);
console.log("4_6 Trianies:", PENTADEKANY_4_6["Trianies"]?.length);
console.log("4_6 Tetranies:", PENTADEKANY_4_6["Tetranies"]?.length);
console.log("4_6 Hexanies:", PENTADEKANY_4_6["Hexanies"]?.length);
console.log("4_6 Dekanies:", PENTADEKANY_4_6["Dekanies"]?.length);
